#!/usr/bin/python
# -*- coding: utf-8 -*-
lista = ["24 de Diciembre","9 de Enero","Agua Buena","Albrook","Alcalde Diaz","Altos de Cerro Viento","Altos de Diablo","Altos de las Acacias","Altos de Tocumen","Altos del Hipódromo","Ancón","Auto Motor","Barriada Tocumen","Bella Vista","Bethania","Brisas del Golf","Cabuyita","Calidonia","Calzada de Amador","Centro Comercial Los Andes N°2","Cerro Batea","Cerro Cocobolo","Cerro Viento","Cerro Viento Rural","Chanis","Chivo Chivo","Chorrillo","Cipreses","Ciudad Belén","Ciudad Bolivar","Ciudad Jardin las Mañanitas","Ciudad Radial","Club del Golf","Colinas de Cerro Batea","Colonia Infantil","Colonia Las Lomas","Condado del Rey","Costa del Este","Don Bosco","Don Bosco","Dorasol","El Chimborazo (Juan diaz)","El Crisol","El Cristo","El Dorado","El Guayabito","El Martillo","El Sitio","El Tecal","Fátima","Hotel Holiday Inn","La Bandera","La Boca","La Cabima","La Concepción","La Doña","La Esmeralda","La Pulida","La Siesta","La Unión","Las Cumbres","Las Lajas","Las Mañanitas","Las Sabanas","Las Trancas","Llano Bonito","Los Andes N° 1","Los Andes N°2","Los Libertadores","Los Pueblos","Lucha Franco","Mano de Piedra","Monte Rico","Morelos","Naranjal","Nueva California","Nueva Libia despues del puente","Nuevo Veranillo","Pan de Azucar","Panamá Viejo","Pedregal Anasal","Pedregalito","Punta Fresca","Punta Pacífica","Punta Paitilla","Quebrada Ancha","Rana de Oro","Residencial Alta Vista","Residencial Altos de San Pedro","Río Abajo","Ruben Dario Paredes","Samaria","San Antonio","San Felipe","San Fernando","San Isidro","San Joaquin","San José","San Miguel","San Pedro","San Vicente","Santa Ana","Santa Clara","Santa Ines","Santa Librada","Santa Marta","Santa Pera","Sonsonate","Templo Bahai","Teremar Plaza Tocumen","Tinajita","Torrijos Carter","Universidad","Urb Dos Rios","Urb el Bosque del Hipodromo","Valle de San Isidro","Valle de Urracá","Versalles Campestre","Villa Adelina","Villa Catalina","Villa de las Fuentes","Villa Grecia","Villa Lucre","Villa Venus","Villa Zaita","Villalobos (Hasta el Naranjal)","Vista Hermosa"]

for x in lista:
	print "ActionButton:"
	print 		"\ttext: \'"+x+"\'"
	print "\ton_press:"
	print "\t\ttx2.text = self.text"
	print "\t\troot.Destino(self.text)"